Messages: #chat! actionbar! title!
  Another:
    No-Permission: "chat! &8(&c&l!&8) &7Не достаточно прав!"
    Plugin-Reload: "chat! &8(&6&l!&8) &7Плагин успешно перезагружен!"
    Arg-Error: "chat! &8(&6&l!&8) &7ОШИБКА 0002441x20, удаляй сервер"
    ActiveBill: "chat! &8(&6&l!&8) &7У вас уже есть неоплаченный счет. Для отмены введите: &d/dn reject"
    NoArg: "chat! &8(&6&l!&8) &7Ты ввёл неправильную суб-команду!"
    NoBill: "chat! &8(&6&l!&8) &7У вас нет активных платежей."
  Bill:
    Reject: "chat! &8(&6&l!&8) &7Счёт успешно аннулирован."
    No-Bill: "chat! &8(&6&l!&8) &7У вас нет активных платежей."
  Json:
    msg: "&7Для пополнения баланса &b&nнажми на меня"
    msg2: "&7После того, как переведёшь средства, введи &9/dn check"
    msg3: "-----------------------------------------------------"
    msg4: "&7Нажми сюда, чтобы пополнить баланс"
  Status:
    Paid: "chat! &8(&6&l!&8) &7Ты успешно пополнил баланс."
    Waiting: "chat! &8(&6&l!&8) &7Ты ещё не оплатил счёт."
    Rejected: "chat! &8(&6&l!&8) &7Платёж отклонен."
    Expired: "chat! &8(&6&l!&8) &7Платёж просрочен."
  Console:
    Message: "&fИгрок &6%player%&f задонатил &e%amount%&f рублей."
    PayLink: "&fИгрок &6%player%&f создал счёт на оплату &e%amount%&f рублей."
    RejectLink: "&fИгрок &6%player%&f отменил счёт."
  Help:
    - "&fПомощь по пополению баланса на сервере"
    - "&8|  &fПополнить баланс - &7/&2dn pay &7<Сумма>"
    - "&8|  &fПроверить оплату - &7/&2dn check"
    - "&8|  &fОтклонить счёт - &7/&2dn reject"

menus:
  admin-gui:
    title: "<$#0C9C29>DraimDonate<$#0ED42C>"
    size: 27
    buttons:
      first:
        material: "BEACON"
        name: "Тестовая кнопка"
        lore:
          - ""
          - "&6Нажмите&F, чтобы обосраться."
          - ""
        type: EXIT
        slots: [ 10 ]
        glowing: false