name: DraimDonate
version: '${project.version}'
main: me.draimgoose.DraimDonate
softdepend: [HeadDatabase]
api-version: 1.17
author: DraimGooSe
commands:
  dn:
    description: Основная команда.
    aliases: [draimdonate, donate, qiwi, dshop]

permissions:
  draimdonate.reload:
    description: Права на команду /dn reload