name: DraimDonate
version: '${project.version}'
main: me.draimgoose.DraimDonate
softdepend: [HeadDatabase]
api-version: 1.17
author: DraimGooSe
commands:
  draimdonate:
    description: Основная команда.
    aliases: [dn, donate, qiwi]

permissions:
  draimdonate.reload:
    description: Права на команду /dn reload